### ISSUE TITLE
WARN Can not index event / mapper_parsing_exception / failed to parse [system.process.cgroup.memory.memsw.limit.bytes] / json_parse_exception / Numeric value xxx out of range of long...

### ISSUE THREAD

**Issue by liar666** [elastic/beats-docker#27]
Hi,

I'm running MetricBeat as explained here: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host

On a (hardened) Debian 8 machine from OVH French provided.

In MetricBeats' log I get a lot of errors like the following:
WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [system.process.cgroup.memory.memsw.limit.bytes]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (18446744073709551615) out of range of long (-9223372036854775808 - 9223372036854775807)

Same error occurs for:
system.process.cgroup.memory.kmem_tcp.limit.bytes
system.process.cgroup.memory.memsw.limit.bytes
system.process.cgroup.memory.stats.hierarchical_memory_limit.bytes

For confirmed bugs, please report:
- Beat Version: MetricBeat 6.0.0 & 6.0.1
- Operating System: Debian 8 / Linux xxx 3.14.32-xxxx-grs-ipv6-64 #1 SMP Tue Jun 30 18:50:21 CEST 2015 x86_64 GNU/Linux
- Docker Version: 1.6.2
- Steps to Reproduce: 

1. run with 
host$docker run --name "MBeats" \
  --volume=/proc:/hostfs/proc:ro \ 
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \ 
  --volume=/:/hostfs:ro \ 
  --net=host 
  docker.elastic.co/beats/metricbeat:6.0.1 -system.hostfs=/hostfs
2. Log into guest
host$docker exec -it "MBeats" /bin/bash
3. Watch logs
guest$ tail -f logs/metricbeat

**Comment by xeraa** [comment]
Looks like your value is 2^64 — for some reason you're not getting the proper metric. I'm wondering if the hardening has to do with that, because [Debian 8 is supported by Metricbeat](https://www.elastic.co/support/matrix).

This repository is only about packaging the Beats in Docker containers, but this problem is IMO in Beats itself. Can you post your problem [in the Beats repo](https://github.com/elastic/beats/issues), please? They should be able to help you out. I took a quick look and couldn't find a similar issue there yet. Thanks!

**Comment by liar666** [comment]
Hi,

Thanks for the prompt reply. I posted here as I thought it might be related to Docker not being run correctly or not able to access the values correctly. Sorry if it was the wrong place.

I've posted the question here: https://github.com/elastic/beats/issues/5854
https://github.com/elastic/beats/issues/5854

**Comment by xeraa** [comment]
No worries — I hope the Beats team can help; otherwise we'll have to reopen this issue here 😅

But even if we have to fix something around the packaging of the Beats, I don't think it should fail like this: If Metricbeat cannot get some fields, the other fields should still be stored and not totally blow up IMO.
