### ISSUE TITLE
Filebeat cannot work, need help!

### ISSUE THREAD

**Issue by tyrantqiao** [elastic/beats-docker#38]
Hello, I cannot use docker's filebeat to get my logs.
[machine+version] centos6 filebeat6.3
1. If I use local filebeat service to work, It can grab any logs I need, But when I run docker's filebeat with my filebeat.yml, It cannot get logs. [This configuration can work on `service filebeat start`] 
2. When the docker's filebeat runs, there are only  `Non-zero metrics` ticking every 30s, I would like to what caused my error. Hopeful you can help me out. Thanks!
3. In my case, I get the logs and then output to kafka cluster.

**Comment by jarpy** [comment]
Hi,

This is probably a good question for the [Beats forum](https://discuss.elastic.co/c/beats). This GitHub project is used for tracking bugs in the build system that creates the Docker images for Beats. If you do try the forum, don't forget to post your `filebeat.yml` and some info about how you are running the container so that people can see what you are trying to do.

Having said that, my initial guess is that your Filebeat container simply can't "see" the files you are interested in. Unless you [do something to make them available](https://docs.docker.com/storage/bind-mounts/), the container won't be able to access logs on the host filesystem.

**Comment by tyrantqiao** [comment]
Thanks jarpy, @jarpy.
