### ISSUE TITLE
Provide Alpine based images

### ISSUE THREAD

**Issue by gittycat** [elastic/beats-docker#7]
Your new official filebeat docker image runs at 245MB.
A simple build based on Alpine goes up to less than 20MB.

Please move your beat images to Alpine.

I'm adding the Dockerfile I currently use for filebeat below.
(adapted from https://github.com/primait/docker-filebeat)
```
FROM alpine:3.5

ENV FILEBEAT_VERSION=5.3.0 \
    FILEBEAT_SHA1=c6f56d1a938889ec9f5db7caea266597f625fcc1

RUN mkdir /etc/filebeat && \
  apk add --no-cache wget && \
  wget -q https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${FILEBEAT_VERSION}-linux-x86_64.tar.gz --no-check-certificate -O filebeat.tar.gz && \
  echo "${FILEBEAT_SHA1}  filebeat.tar.gz" | sha1sum -c - && \
  tar xzvf filebeat.tar.gz && \
  cp filebeat-*/filebeat /usr/local/bin && \
  rm -rf filebeat*

WORKDIR /etc/filebeat
COPY filebeat.yml /etc/filebeat/
COPY filebeat.template.json /etc/filebeat/
COPY filebeat.template-es2x.json /etc/filebeat/
COPY inject.sh /usr/local/bin

ENTRYPOINT []
CMD [ "filebeat", "-e" ]
```

**Comment by jarpy** [comment]
Hi,

We have no plans to use Alpine for any of our images in the future. All the other Elastic products have faced problems due to limitations in Alpine and musl libc. While Beats are the most likely of all Elastic products to run well on Alpine, we've chosen consistency across the stack as the primary thing to optimize for. We'll actually be converging all our images to a Centos 7 base soon.

**Comment by murdav** [comment]
Detail explanation for people coming from Google:
https://www.elastic.co/blog/docker-base-centos7
